from upstash_py.utils.exception import (
    handle_geosearch_exceptions,
    handle_non_deprecated_zrange_exceptions,
    handle_zrangebylex_exceptions
)
from pytest import raises


def test_handle_geosearch_exceptions() -> None:
    pass
